username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
timeout: 10s

targets:
  switch-lan:
    address: switch-lan:57400

subscriptions:
  srl-system-performance:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /platform/control[slot=*]/cpu[index=all]/total

  srl-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/*]/statistics/in-broadcast-packets
      - /interface[name=ethernet-1/*]/statistics/in-error-packets
      - /interface[name=ethernet-1/*]/traffic-rate

  srl-acl-statistics:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv4]/entry[sequence-id=20]/statistics/    
            
outputs:
  
  prom-output:
    type: prometheus
    listen: :9273        
